CONFIG_NAME: coco

dataset_name: coco
data_dir: ../data/coco

gpu_id: 0
imsize: 256
z_dim: 100
cond_dim: 256
manual_seed: 100
cuda: True

stamp: 'normal'
state_epoch: 0
max_epoch: 301
batch_size: 32
nf: 32
ch_size: 3

model: base

gen_interval: 1
test_interval: 5
save_interval: 5

truncation: True
trunc_rate: 0.88

sample_times: 1
npz_path: ../data/coco/npz/coco_val256_FIDK0.npz
example_captions: ./example_captions/coco.txt
samples_save_dir: ./samples/coco/
checkpoint: ./saved_models/coco/pretrained/state_epoch_290.pth

save_image: False
val_save_dir: ./vals/coco/

TEXT:
    WORDS_NUM: 18
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 5
    DAMSM_NAME: ../data/coco/DAMSMencoder/text_encoder100.pth
    